apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: USER
          value: 999:999
        - name: MYSQL_ROOT_PASSWORD
          value: 'PQThai29112003'
        - name: MYSQL_DATABASE
          value: 'randomNumberDB'
        - name: MYSQL_USER
          value: 'kenphung'
        - name: MYSQL_HOST
          value: '%'
          # Assign host ip hear
        - name: MYSQL_PASSWORD
          value: 'PQThai29112003'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-data
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 20Gi


# # PERSISTENT VOLUME CLAIM
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pvc
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi